### ISSUE TITLE
pokemanpcr的问题

### ISSUE THREAD

**Issue by reF1nd** [GWYOG/GWYOG-Hoshino-plugins#11]
在一开始加载插件的时候报错了
![1](https://user-images.githubusercontent.com/24762710/98527103-8de5ba80-22b5-11eb-9efc-b50e146e6e94.jpg)

**Comment by GWYOG** [comment]
新版插件改用Hoshino的头像资源包作为卡库，对res/img/priconne/unit中的头像文件名格式有比较严格的要求
我这儿并没遇到这个问题，过会我会详细查下是哪个头像文件导致的

**Comment by GWYOG** [comment]
估计是一张文件名为`icon_unit_390100.png`的霸瞳头像导致的，晚点我会修复这个bug

**Comment by reF1nd** [comment]
要说文件名的话，我这个文件夹里还有`cropped_avatar.png`和`kokkoro_stamp.png`这两个和其他图片命名格式不同的图片，会是因为这个吗？

**Comment by GWYOG** [comment]
啊，那些无所谓的，因为代码里只考虑以`icon_unit_`开头的文件名
