### ISSUE TITLE
反并发插件失效了

### ISSUE THREAD

**Issue by lolikyo** [GWYOG/GWYOG-Hoshino-plugins#29]
更新 hoshino最新版本后反并发插件不能用了
![image](https://user-images.githubusercontent.com/49865203/122630791-05f04a80-d0f9-11eb-8ab9-509f37f45f83.png)

**Comment by clacknya** [comment]
目前将
``` python
sf = trigger_words_dict[trigger_word]
```
改为
``` python
sf = trigger_words_dict[trigger_word][0]
```
可解

**Comment by lolikyo** [comment]
![image](https://user-images.githubusercontent.com/49865203/129026669-d0031717-817e-45aa-aab4-e4faaa64a425.png)
我是for遍历了一遍，也不报错了😂
