### ISSUE TITLE
Could I merge these games into HoshinoBot?

### ISSUE THREAD

**Issue by Ice-Cirno** [GWYOG/GWYOG-Hoshino-plugins#3]
Hello, I am the author of HoshinoBot.
It is a great charming game for pcrbots! You've made a great work!!

您好，我是HoshinoBot的作者。
您开发的小游戏非常棒！Great work！！

Could I please merge pcrdescguess and pcravatarguess into the master branch of [HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)? Of course, I will acknowledge your id and refer to your repo in the documents.

我能否将pcrdescguess和pcravatarguess这两个小游戏合并至[HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)的master分支？当然，我会鸣谢您的id，并注明您的项目地址。

**Comment by GWYOG** [comment]
Of course, go ahead and do whatever you want. 
不过由于协程有时会导致判定对局结束与判定有人猜对的先后顺序相反，这两个插件可能还存在一些潜在的bug（一般比较少出现），如果您有重构代码意向的话是再好不过了。

**Comment by Ice-Cirno** [comment]
> 不过由于协程有时会导致判定对局结束与判定有人猜对的先后顺序相反，这两个插件可能还存在一些潜在的bug（一般比较少出现），如果您有重构代码意向的话是再好不过了。

这个问题我也观测到了，目前已尝试修复，不知是否能完全解决。
代码我也进行了一些重构，将重复的代码提取至公用类。目前两个小游戏的实现均在80行以内（不记文件开头的注释）

**Comment by GWYOG** [comment]
嗯嗯，那再好不过了。其实我也一直有重新整理下代码的想法的(毕竟重复代码实在太多了...)，无奈懒癌发作。

此外，插件使用的从兰德索尔图书馆获取的角色生日、身高、体重、喜好等数据并入HoshinoBot本体的话那就再好不过了，这些数据还有不少挖掘空间，比如可以做在角色生日当天的生日祝福推送等等。
期待新版本的HoshinoBot~
